#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BluetoothLEExplorer.Droid.Resource", IsApplication=true)]

namespace BluetoothLEExplorer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int PlanritningSpree = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int positionCursor = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int BaconButton = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int DevicesTable = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int ScanButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int b1 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int b2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int b3 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int bgID = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int dotID = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int myButton = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ScannerHome = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
